#postgresql:
#  database: aiohttpdemo_polls
#  user: aiohttpdemo_user
#  password: aiohttpdemo_user
#  host: localhost
#  port: 5432
#  minsize: 1
#  maxsize: 5
database:
  drivername: mysql
  database: aiohttp_test
  username: root
  password: "123456"
  host: 192.168.92.134
  port: 3306
  minsize: 1
  maxsize: 5

host: 127.0.0.1
port: 8080
